
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/log:/var/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
